formatter: markdown table

header-from: docs/header.md
footer-from: docs/footer.md

recursive:
  enabled: false

sections:
  show:
    - header
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs
    - footer

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  escape: true
  indent: 3
  required: true
  type: true
